// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    let session = data.session;

    // `getSession` pode devolver um access_token já expirado (ou a segundos de
    // expirar) quando o refresh automático não rodou — o servidor então
    // rejeita com "Unauthorized: Invalid token". Renovamos antes de enviar.
    const expiresAt = session?.expires_at ? session.expires_at * 1000 : 0;
    if (session && expiresAt && expiresAt - Date.now() < 30_000) {
      const { data: refreshed } = await supabase.auth.refreshSession();
      session = refreshed.session ?? session;
    }

    const token = session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);

